from .llama import LlamaMixQForCausalLM
from .opt import OptMixForCausalLM
#from .mistral import MistralMixForCausalLM
from .gptj import GPTJMixForCausalLM
from .falcon import FalconMixForCausalLM
from .baichuan import BaichuanMixQForCausalLM
from .glm import ChatGLMMixQForCausalLM
from .qwen2 import Qwen2MixQForCausalLM
from .deepseek_v2 import deepseek_v2MixQForCausalLM